twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
    paths:
        '%kernel.project_dir%/public/build/app': app_path

when@test:
    twig:
        strict_variables: true
